#!/bin/bash

# Exit on first error.
set -e

umask 077

# Configure versions
TOMCAT_VERSION='8.0.23'
SCALA_VERSION='2.11.4'
SBT_VERSION='0.13.8'

# Setup dir references
OPENSHIFT_RUNTIME_DIR=${OPENSHIFT_DIY_DIR}runtime/
ROOT_DIR=${OPENSHIFT_RUNTIME_DIR}
#BUILD_DIR=${OPENSHIFT_TMP_DIR}/build
SBT_PATH=${ROOT_DIR}sbt/
SBT_DIR=${ROOT_DIR}.sbt/
IVY_DIR=${ROOT_DIR}.ivy

mkdir -p $ROOT_DIR
mkdir -p $SBT_DIR
mkdir -p $IVY_DIR

cd $ROOT_DIR

echo "Downloading Apache Tomcat $TOMCAT_VERSION..."
curl -s -o apache-tomcat-$TOMCAT_VERSION.tar.gz http://www.us.apache.org/dist/tomcat/tomcat-8/v$TOMCAT_VERSION/bin/apache-tomcat-$TOMCAT_VERSION.tar.gz
tar xzf apache-tomcat-$TOMCAT_VERSION.tar.gz
rm -f apache-tomcat-$TOMCAT_VERSION.tar.gz
ln -sf apache-tomcat-$TOMCAT_VERSION apache-tomcat
pushd apache-tomcat-$TOMCAT_VERSION
rm -rf logs
ln -s $OPENSHIFT_LOG_DIR logs
pushd webapps
rm -rf *
popd
popd

echo "Downloading scala $SCALA_VERSION..."
curl -s -o scala-$SCALA_VERSION.tgz http://downloads.typesafe.com/scala/$SCALA_VERSION/scala-$SCALA_VERSION.tgz
tar xzf scala-$SCALA_VERSION.tgz
rm -f scala-$SCALA_VERSION.tgz
ln -sf scala-$SCALA_VERSION scala

echo "Downloading sbt $SBT_VERSION..."
curl -L -o sbt.tgz -O http://dl.bintray.com:80/sbt/native-packages/sbt/${SBT_VERSION}/sbt-${SBT_VERSION}.tgz
tar zxvf sbt.tgz
rm -f xzf sbt.tgz

cd $OPENSHIFT_REPO_DIR

echo "Compiling..."
$SBT_PATH/bin/sbt -sbt-dir $SBT_DIR -ivy $IVY_DIR -mem 512 package
#FIXME: Should deduce WAR version
mv target/scala-2.11/beecam_2.11-0.1.war ${ROOT_DIR}apache-tomcat/webapps/ROOT.war
